# Generated by Django 5.1 on 2024-09-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDev', '0004_autonomie_informationpersonnel_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomie',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='integration',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='ponctualite',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='satisfaction',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='savoirformation',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='sensduservice',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='tenacite',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='testtechniquefullstack',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='testtechniquejavascript',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AddField(
            model_name='testtechniquepython',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testDev.informationpersonnel'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='depasse_par_situation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='integration',
            name='reaction_remarque_negative',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='integration',
            name='type_personnes_preferees',
            field=models.TextField(),
        ),
    ]
